import Head from "next/head";
import { getAllPosts } from "../data/ads";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import style from "../styles/Home.module.css";
import { addRequestMeta } from "next/dist/server/request-meta";
import AdPreview from "../components/AdPreview";
import AdPreviewDb from "../components/AdPreviewDb";
import HomeFooter from "../components/HomeFooter";
import SearchHeader from "../components/SearchHeader";
import SearchFilter from "../components/SearchFilter";

import { useState, useEffect } from "react";
import { collection, getDocs } from "firebase/firestore";
import { firebaseApp, storage, db } from "../connect/firebase";
import { ref, getDownloadURL, listAll } from "firebase/storage";
import {
  getImageListItemBarUtilityClass,
  useIsFocusVisible,
} from "@mui/material";
import { withCoalescedInvoke } from "next/dist/lib/coalesced-function";

export default function Home() {
  const [ads, setAds] = useState([]);
  const adsCollectionRef = collection(db, "ads");

  useEffect(() => {
    const getAds = async () => {
      const data = await getDocs(adsCollectionRef);
      setAds(data.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
    };
    getAds();
  }, []);

  const checkAds = () => {
    if (ads.length > 0 && ads[0].previewImg !== "") {
      ads.map((ad, index) => {
        getImgUrl(ads, ad, index);
      });
    }
  };

  useEffect(() => {
    checkAds();
  }, [ads]);

  const getImgUrl = async (ads, ad, index) => {
    let imgRef = ref(storage, "ad_images/" + ad.adImg);
    getDownloadURL(imgRef).then((url) => {
      if (typeof ads[index].previewImg == "undefined") {
        ads[index].previewImg = url;
        setAds(ads);
      }
    });
  };

  const getAds = () => {
    return ads.map((ad) => {
      console.log(ad);
      return (
        <div key={ad.id} className={style.ad_preview_box_desktop}>
          <div className={style.time_ago_desktop}>• 2h ago</div>
          <div className={style.desktop_ad_box_flex}>
            <div className={style.desktop_ad_img}>
              <img src={ad.previewImg} />
            </div>

            <div className={style.desktop_ad_content}>
              <div className={style.desktop_ad_title}>{ad.adTitle}</div>
              <div className={style.desktop_ad_location}>
                <img src="../../icons/pin.svg" /> Skopje
              </div>
              <div className={style.desktop_price}>
                {ad.adPrice} {ad.adCurrency}{" "}
              </div>

              <div className={style.ad_stats}>
                <div className={style.ad_data}>
                  <div className={style.ad_data_icon}>
                    <img src="../../icons/pin.svg" />
                  </div>
                  <div className={style.ad_data_number}>123</div>
                </div>

                <div className={style.ad_data}>
                  <div className={style.ad_data_icon}>
                    <img src="../../icons/pin.svg" />
                  </div>
                  <div className={style.ad_data_number}>12</div>
                </div>

                <div className={style.ad_data}>
                  <div className={style.ad_data_icon}>
                    <img src="../../icons/pin.svg" />
                  </div>
                  <div className={style.ad_data_number}>5</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      );
    });
  };

  return (
    <div>
      <Head>
        <title>Hitno.mk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
      </Head>

      <div className={styles.desktop_header}>
        <div className={styles.desktop_size}>
          <div className={styles.desktop_logo}>
            <img src="../icons/hitno.png" />
          </div>
          <div className={styles.desktop_menu_btn}>
            <img src="../icons/more.svg" />
          </div>
        </div>
      </div>

      <div className={styles.desktop_container}>
        <div className={styles.desktop_filter_section}>
          <SearchFilter />
        </div>

        <div className={styles.container}>
          <SearchHeader />

          {getAds()}

          <HomeFooter />
        </div>
      </div>
    </div>
  );
}
