import React from "react";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import { storage, db, firebaseApp } from "../../connect/firebase";
import Link from "next/link";
import Head from "next/head";
import HomeFooter from "../../components/HomeFooter";
import SearchHeader from "../../components/SearchHeader";
import SearchFilter from "../../components/SearchFilter";
import {
  getStorage,
  imageURL,
  getStorageRef,
  ref,
  listAll,
  getDownloadURL,
  pathReference,
} from "firebase/storage";

import {
  collection,
  getDocs,
  addDoc,
  deleteDoc,
  doc,
  onSnapshot,
  where,
  query,
  orderBy,
  serverTimestamp,
} from "firebase/firestore";

import { getAuth, signOut, onAuthStateChanged, reload } from "firebase/auth";

function Index() {
  const [currentloginEmail, setcurrentLoginEmail] = useState("");
  const [currentloginId, setcurrentLoginId] = useState("");

  const [ads, setAds] = useState([]);

  const [dataStatus, setDataStatus] = useState("");

  //init services
  const router = useRouter();
  //collection ref
  const colRef = collection(db, "ads");

  // const createTask = async () => {
  //   addDoc(colRef, {
  //     taskTitle: taskTitle,
  //     taskDesc: taskDesc,
  //     createdAt: serverTimestamp(),
  //     userLoginId: currentloginId,
  //   });
  //   setTaskTitle("");
  //   setTaskDesc("");
  //   setDataStatus("Task created");
  // };

  const signOutUser = async () => {
    signOut(auth)
      .then(() => {
        console.log("User signed out");
        setcurrentLoginEmail("");
        setcurrentLoginId("");
      })
      .catch((err) => {
        console.log(err.message);
      });
  };

  useEffect(() => {
    const q = query(
      collection(db, "ads"),
      // where("userLoginId", "==", currentloginId),
      orderBy("createdAt", "desc")
    );

    onSnapshot(q, (snapshot) => {
      let ads = [];
      snapshot.docs.forEach((doc) => {
        ads.push({ ...doc.data(), id: doc.id });
        setAds(ads);
        console.log(dataStatus);
      });
    });
  }, [dataStatus]);

  useEffect(() => {
    const auth = getAuth();

    onAuthStateChanged(auth, (user) => {
      if (user) {
        setcurrentLoginEmail(user.email);
        setcurrentLoginId(user.uid);
        setDataStatus("Data exhange started");
      } else {
        router.push("../login");
      }
    });
  }, [currentloginId]);

  return (
    <div className={styles.main_row}>
      <Head>
        <title>Hitno.mk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
      </Head>

      <div className={styles.desktop_header}>
        <div className={styles.desktop_size}>
          <div className={styles.desktop_logo}>
            <img src="../icons/hitno.png" alt="" />
          </div>
          <div className={styles.desktop_menu_btn}>
            <img src="../icons/more.svg" alt="" />
          </div>
        </div>
      </div>

      <div className={styles.desktop_container}>
        <div className={styles.desktop_filter_section}>
          <SearchFilter />

          {/*<HomeCategories />*/}
        </div>

        <div className={styles.container}>
          <SearchHeader />

          {ads.map((ad) => {
            return (
              <div>
                <Link href={`home/${ad.adId}`} key={ad.adId}>
                  <div className={styles.ad_preview_box_desktop}>
                    <div className={styles.time_ago_desktop}>• 2h ago</div>
                    <div className={styles.desktop_ad_box_flex}>
                      <div className={styles.desktop_ad_img}>
                        <img src={ad.imgUrl} alt="" />
                      </div>

                      <div className={styles.desktop_ad_content}>
                        <div className={styles.desktop_ad_title}>
                          {ad.adTitle}
                        </div>
                        <div className={styles.desktop_ad_location}>
                          <img src="../icons/pin.svg" alt="" /> Skopje
                        </div>
                        <div className={styles.desktop_price}>
                          {ad.adPrice} {ad.adCurrency}{" "}
                        </div>

                        <div className={styles.ad_stats}>
                          <div className={styles.ad_data}>
                            <div className={styles.ad_data_icon}>
                              <img src="../icons/eye.svg" alt="" />
                            </div>
                            <div className={styles.ad_data_number}>123</div>
                          </div>

                          <div className={styles.ad_data}>
                            <div className={styles.ad_data_icon}>
                              <img src="../icons/hart.svg" alt="" />
                            </div>
                            <div className={styles.ad_data_number}>12</div>
                          </div>

                          <div className={styles.ad_data}>
                            <div className={styles.ad_data_icon}>
                              <img src="../icons/share.svg" alt="" />
                            </div>
                            <div className={styles.ad_data_number}>5</div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </Link>
              </div>
            );
          })}
          <HomeFooter />
        </div>
        

        <div className={styles.desktop_signup_secton}>
          <div className={styles.desktop_signup_header}>
            Продади се за 24 часа!
          </div>
          <div className={styles.desktop_signup_buttons}>
            <div className={styles.d_signup_btn}>
              <img src="../icons/facebook.svg" alt=" " /> Зачлени се со Facebook
            </div>
            <div className={styles.d_signup_btn}>
              <img src="../icons/google.svg" alt=" " /> Зачлени се со Google
            </div>
          </div>

          <div className={styles.or_splitter}>
            <div className={styles.split_line}></div>
            <div className={styles.split_text}>or</div>
            <div className={styles.split_line}></div>
          </div>
          <div className={styles.email_signup_btn}>Зачлени се со eMail</div>
          <div className={styles.terms_text}>
            Зачленувајќи се, се сложуваш со нашата
            <a href=""> Полиса на Корисници</a> и
            <a href=""> Полиса на приватност</a>, вклучувајќи и
            <a href=""> Употреба на колачиња.</a>
          </div>

          <div className={styles.already_have_text}>
            Веќе имаш сметка кај нас?
          </div>
          <div className={styles.d_signin_btn}>Најави се</div>
        </div>
      </div>
    </div>
  );
}

export default Index;
